// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package client

import (
	"github.com/infiotinc/gqlgenc/client/transport"
)

type PostCreateInput struct {
	Text string `json:"text"`
}

type UploadFilesMapInput struct {
	Somefile transport.Upload `json:"somefile"`
}
