// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package client

import (
	"github.com/infiotinc/gqlgenc/client/transport"
)

type PostCreateInput struct {
	Text string `json:"text"`
}

type SomeExtraType struct {
	Child *SomeExtraTypeChild `json:"child"`
}

type SomeExtraTypeChild struct {
	Child *SomeExtraTypeChildChild `json:"child"`
}

type SomeExtraTypeChildChild struct {
	ID string `json:"id"`
}

type UploadFilesMapInput struct {
	Somefile transport.Upload `json:"somefile"`
}
