// Code generated by github.com/infiotinc/gqlgenc, DO NOT EDIT.

package graph

import (
	"context"
	"example/somelib"

	"github.com/infiotinc/gqlgenc/client"
)

type Client struct {
	Client *client.Client
}

type Query struct {
	Room *Chatroom "json:\"room\" graphql:\"room\""
}
type Mutation struct {
	Post Message "json:\"post\" graphql:\"post\""
}
type Subscription struct {
	MessageAdded Message "json:\"messageAdded\" graphql:\"messageAdded\""
}
type GetRoom struct {
	Room *struct {
		Name string "json:\"name\""
	} "json:\"room\""
}
type SubscribeMessageAdded struct {
	MessageAdded struct {
		ID string "json:\"id\""
	} "json:\"messageAdded\""
}

const GetRoomDocument = `query GetRoom ($name: String!) {
	room(name: $name) {
		name
	}
}
`

func (c *Client) GetRoom(ctx context.Context, name string) (*GetRoom, error) {
	vars := map[string]interface{}{
		"name": name,
	}

	var res GetRoom
	if err := c.Client.Query(ctx, "GetRoom", GetRoomDocument, vars, &res); err != nil {
		return nil, err
	}

	return &res, nil
}

const GetRoomCustomDocument = `query GetRoomCustom ($name: String!) {
	room(name: $name) {
		name
	}
}
`

func (c *Client) GetRoomCustom(ctx context.Context, name string) (*somelib.CustomRoom, error) {
	vars := map[string]interface{}{
		"name": name,
	}

	var res somelib.CustomRoom
	if err := c.Client.Query(ctx, "GetRoomCustom", GetRoomCustomDocument, vars, &res); err != nil {
		return nil, err
	}

	return &res, nil
}

const SubscribeMessageAddedDocument = `subscription SubscribeMessageAdded {
	messageAdded(roomName: "test") {
		id
	}
}
`

type MessageSubscribeMessageAdded struct {
	Data  *SubscribeMessageAdded
	Error error
}

func (c *Client) SubscribeMessageAdded(ctx context.Context) (chan MessageSubscribeMessageAdded, error) {
	vars := map[string]interface{}{}

	sub, err := c.Client.Subscription(ctx, "SubscribeMessageAdded", SubscribeMessageAddedDocument, vars)
	if err != nil {
		return nil, err
	}

	ch := make(chan MessageSubscribeMessageAdded)

	go func() {
		for sub.Next() {
			res := sub.Get()

			var datares MessageSubscribeMessageAdded
			if len(res.Errors) > 0 {
				datares.Error = res.Errors
			}

			err := res.UnmarshalData(&datares.Data)
			if datares.Error == nil && err != nil {
				datares.Error = err
			}

			ch <- datares
		}
		if err := sub.Err(); err != nil {
			ch <- MessageSubscribeMessageAdded{
				Error: err,
			}
		}
		close(ch)
	}()

	return ch, nil
}
