name: Full Codegen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.15', '1.16', '1.17', '1.18' ]
    name: Run ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Full Codegen
      run: make example-fullgen

    - name: Test Example
      run: make example-test

    - name: Codegen
      run: make example-genall

    - name: Test Example
      run: make example-test
